#pragma once

// Do not edit this file, it is automatically generated by CMAKE!

namespace Pinetime {
  class Version {
    public:
      static uint32_t Major() {return major;}
      static uint32_t Minor() {return minor;}
      static uint32_t Patch() {return patch;}
    private:
      static constexpr uint32_t major = 0;
      static constexpr uint32_t minor = 4;
      static constexpr uint32_t patch = 0;
  };
}
